# Generated by Django 2.2.3 on 2019-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_auto_20191102_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
