# Generated by Django 2.2.3 on 2019-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_auto_20191102_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
