# Generated by Django 2.2.3 on 2019-11-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_auto_20191020_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
