# Generated by Django 2.2.3 on 2019-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_auto_20191102_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(default='--------------------------', max_length=500),
        ),
    ]
