# Generated by Django 2.2.3 on 2019-11-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_auto_20191103_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(default='لايوجد وصف', max_length=500),
        ),
    ]
